// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ-Xj8fBbBS_lm2uqdO1matMvNj_Kz2gc',
    appId: '1:374313640637:web:bdb791c6ed19ebe16c8dd4',
    messagingSenderId: '374313640637',
    projectId: 'desafio-ambisis',
    authDomain: 'desafio-ambisis.firebaseapp.com',
    storageBucket: 'desafio-ambisis.appspot.com',
    measurementId: 'G-NB0CSYREMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Gd1yiu4OzcvxKeuZlCGkZ3BLieqjqyU',
    appId: '1:374313640637:android:5ccc8a28a87320af6c8dd4',
    messagingSenderId: '374313640637',
    projectId: 'desafio-ambisis',
    storageBucket: 'desafio-ambisis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg8fTtL0vXVQt2s7InQ3i0gL5Oyi7nVtM',
    appId: '1:374313640637:ios:d2552a309f110bcf6c8dd4',
    messagingSenderId: '374313640637',
    projectId: 'desafio-ambisis',
    storageBucket: 'desafio-ambisis.appspot.com',
    iosBundleId: 'com.example.desafioFlutterAmbisis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg8fTtL0vXVQt2s7InQ3i0gL5Oyi7nVtM',
    appId: '1:374313640637:ios:c2c073e287d617336c8dd4',
    messagingSenderId: '374313640637',
    projectId: 'desafio-ambisis',
    storageBucket: 'desafio-ambisis.appspot.com',
    iosBundleId: 'com.example.desafioFlutterAmbisis.RunnerTests',
  );
}
